// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

#include "protoh/commands.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace questnav {
namespace protos {
namespace commands {
PROTOBUF_CONSTEXPR ProtobufQuestNavPoseResetPayload::ProtobufQuestNavPoseResetPayload(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.target_pose_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProtobufQuestNavPoseResetPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavPoseResetPayloadDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavPoseResetPayloadDefaultTypeInternal() {}
  union {
    ProtobufQuestNavPoseResetPayload _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavPoseResetPayloadDefaultTypeInternal _ProtobufQuestNavPoseResetPayload_default_instance_;
PROTOBUF_CONSTEXPR ProtobufQuestNavCommand::ProtobufQuestNavCommand(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.command_id_)*/0u
  , /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct ProtobufQuestNavCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavCommandDefaultTypeInternal() {}
  union {
    ProtobufQuestNavCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavCommandDefaultTypeInternal _ProtobufQuestNavCommand_default_instance_;
PROTOBUF_CONSTEXPR ProtobufQuestNavCommandResponse::ProtobufQuestNavCommandResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.command_id_)*/0u
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProtobufQuestNavCommandResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavCommandResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavCommandResponseDefaultTypeInternal() {}
  union {
    ProtobufQuestNavCommandResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavCommandResponseDefaultTypeInternal _ProtobufQuestNavCommandResponse_default_instance_;
}  // namespace commands
}  // namespace protos
}  // namespace questnav
static ::_pb::Metadata file_level_metadata_commands_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_commands_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_commands_2eproto = nullptr;

const uint32_t TableStruct_commands_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload, _impl_.target_pose_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _impl_.command_id_),
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommand, _impl_.payload_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommandResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommandResponse, _impl_.command_id_),
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommandResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::questnav::protos::commands::ProtobufQuestNavCommandResponse, _impl_.error_message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload)},
  { 7, -1, -1, sizeof(::questnav::protos::commands::ProtobufQuestNavCommand)},
  { 17, -1, -1, sizeof(::questnav::protos::commands::ProtobufQuestNavCommandResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::questnav::protos::commands::_ProtobufQuestNavPoseResetPayload_default_instance_._instance,
  &::questnav::protos::commands::_ProtobufQuestNavCommand_default_instance_._instance,
  &::questnav::protos::commands::_ProtobufQuestNavCommandResponse_default_instance_._instance,
};

const char descriptor_table_protodef_commands_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016commands.proto\022\030questnav.protos.comman"
  "ds\032\020geometry3d.proto\"R\n ProtobufQuestNav"
  "PoseResetPayload\022.\n\013target_pose\030\001 \001(\0132\031."
  "wpi.proto.ProtobufPose3d\"\317\001\n\027ProtobufQue"
  "stNavCommand\022;\n\004type\030\001 \001(\0162-.questnav.pr"
  "otos.commands.QuestNavCommandType\022\022\n\ncom"
  "mand_id\030\002 \001(\r\022X\n\022pose_reset_payload\030\n \001("
  "\0132:.questnav.protos.commands.ProtobufQue"
  "stNavPoseResetPayloadH\000B\t\n\007payload\"]\n\037Pr"
  "otobufQuestNavCommandResponse\022\022\n\ncommand"
  "_id\030\001 \001(\r\022\017\n\007success\030\002 \001(\010\022\025\n\rerror_mess"
  "age\030\003 \001(\t*C\n\023QuestNavCommandType\022\034\n\030COMM"
  "AND_TYPE_UNSPECIFIED\020\000\022\016\n\nPOSE_RESET\020\001BC"
  "\n%gg.questnav.questnav.protos.generated\252"
  "\002\031QuestNav.Protos.Generatedb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_commands_2eproto_deps[1] = {
  &::descriptor_table_geometry3d_2eproto,
};
static ::_pbi::once_flag descriptor_table_commands_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_commands_2eproto = {
    false, false, 595, descriptor_table_protodef_commands_2eproto,
    "commands.proto",
    &descriptor_table_commands_2eproto_once, descriptor_table_commands_2eproto_deps, 1, 3,
    schemas, file_default_instances, TableStruct_commands_2eproto::offsets,
    file_level_metadata_commands_2eproto, file_level_enum_descriptors_commands_2eproto,
    file_level_service_descriptors_commands_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_commands_2eproto_getter() {
  return &descriptor_table_commands_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_commands_2eproto(&descriptor_table_commands_2eproto);
namespace questnav {
namespace protos {
namespace commands {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* QuestNavCommandType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_commands_2eproto);
  return file_level_enum_descriptors_commands_2eproto[0];
}
bool QuestNavCommandType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ProtobufQuestNavPoseResetPayload::_Internal {
 public:
  static const ::wpi::proto::ProtobufPose3d& target_pose(const ProtobufQuestNavPoseResetPayload* msg);
};

const ::wpi::proto::ProtobufPose3d&
ProtobufQuestNavPoseResetPayload::_Internal::target_pose(const ProtobufQuestNavPoseResetPayload* msg) {
  return *msg->_impl_.target_pose_;
}
void ProtobufQuestNavPoseResetPayload::clear_target_pose() {
  if (GetArenaForAllocation() == nullptr && _impl_.target_pose_ != nullptr) {
    delete _impl_.target_pose_;
  }
  _impl_.target_pose_ = nullptr;
}
ProtobufQuestNavPoseResetPayload::ProtobufQuestNavPoseResetPayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
}
ProtobufQuestNavPoseResetPayload::ProtobufQuestNavPoseResetPayload(const ProtobufQuestNavPoseResetPayload& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProtobufQuestNavPoseResetPayload* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.target_pose_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_target_pose()) {
    _this->_impl_.target_pose_ = new ::wpi::proto::ProtobufPose3d(*from._impl_.target_pose_);
  }
  // @@protoc_insertion_point(copy_constructor:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
}

inline void ProtobufQuestNavPoseResetPayload::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.target_pose_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProtobufQuestNavPoseResetPayload::~ProtobufQuestNavPoseResetPayload() {
  // @@protoc_insertion_point(destructor:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtobufQuestNavPoseResetPayload::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.target_pose_;
}

void ProtobufQuestNavPoseResetPayload::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProtobufQuestNavPoseResetPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.target_pose_ != nullptr) {
    delete _impl_.target_pose_;
  }
  _impl_.target_pose_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtobufQuestNavPoseResetPayload::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .wpi.proto.ProtobufPose3d target_pose = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_target_pose(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtobufQuestNavPoseResetPayload::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .wpi.proto.ProtobufPose3d target_pose = 1;
  if (this->_internal_has_target_pose()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::target_pose(this),
        _Internal::target_pose(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  return target;
}

size_t ProtobufQuestNavPoseResetPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .wpi.proto.ProtobufPose3d target_pose = 1;
  if (this->_internal_has_target_pose()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.target_pose_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtobufQuestNavPoseResetPayload::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProtobufQuestNavPoseResetPayload::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtobufQuestNavPoseResetPayload::GetClassData() const { return &_class_data_; }


void ProtobufQuestNavPoseResetPayload::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavPoseResetPayload*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavPoseResetPayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_target_pose()) {
    _this->_internal_mutable_target_pose()->::wpi::proto::ProtobufPose3d::MergeFrom(
        from._internal_target_pose());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavPoseResetPayload::CopyFrom(const ProtobufQuestNavPoseResetPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.commands.ProtobufQuestNavPoseResetPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufQuestNavPoseResetPayload::IsInitialized() const {
  return true;
}

void ProtobufQuestNavPoseResetPayload::InternalSwap(ProtobufQuestNavPoseResetPayload* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.target_pose_, other->_impl_.target_pose_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtobufQuestNavPoseResetPayload::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_commands_2eproto_getter, &descriptor_table_commands_2eproto_once,
      file_level_metadata_commands_2eproto[0]);
}

// ===================================================================

class ProtobufQuestNavCommand::_Internal {
 public:
  static const ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload& pose_reset_payload(const ProtobufQuestNavCommand* msg);
};

const ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload&
ProtobufQuestNavCommand::_Internal::pose_reset_payload(const ProtobufQuestNavCommand* msg) {
  return *msg->_impl_.payload_.pose_reset_payload_;
}
void ProtobufQuestNavCommand::set_allocated_pose_reset_payload(::questnav::protos::commands::ProtobufQuestNavPoseResetPayload* pose_reset_payload) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (pose_reset_payload) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pose_reset_payload);
    if (message_arena != submessage_arena) {
      pose_reset_payload = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pose_reset_payload, submessage_arena);
    }
    set_has_pose_reset_payload();
    _impl_.payload_.pose_reset_payload_ = pose_reset_payload;
  }
  // @@protoc_insertion_point(field_set_allocated:questnav.protos.commands.ProtobufQuestNavCommand.pose_reset_payload)
}
ProtobufQuestNavCommand::ProtobufQuestNavCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.commands.ProtobufQuestNavCommand)
}
ProtobufQuestNavCommand::ProtobufQuestNavCommand(const ProtobufQuestNavCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProtobufQuestNavCommand* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.command_id_){}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.command_id_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.command_id_));
  clear_has_payload();
  switch (from.payload_case()) {
    case kPoseResetPayload: {
      _this->_internal_mutable_pose_reset_payload()->::questnav::protos::commands::ProtobufQuestNavPoseResetPayload::MergeFrom(
          from._internal_pose_reset_payload());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:questnav.protos.commands.ProtobufQuestNavCommand)
}

inline void ProtobufQuestNavCommand::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0}
    , decltype(_impl_.command_id_){0u}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_payload();
}

ProtobufQuestNavCommand::~ProtobufQuestNavCommand() {
  // @@protoc_insertion_point(destructor:questnav.protos.commands.ProtobufQuestNavCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtobufQuestNavCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_payload()) {
    clear_payload();
  }
}

void ProtobufQuestNavCommand::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProtobufQuestNavCommand::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:questnav.protos.commands.ProtobufQuestNavCommand)
  switch (payload_case()) {
    case kPoseResetPayload: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.pose_reset_payload_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void ProtobufQuestNavCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.commands.ProtobufQuestNavCommand)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.command_id_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.command_id_));
  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtobufQuestNavCommand::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .questnav.protos.commands.QuestNavCommandType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::questnav::protos::commands::QuestNavCommandType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint32 command_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.command_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .questnav.protos.commands.ProtobufQuestNavPoseResetPayload pose_reset_payload = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_pose_reset_payload(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtobufQuestNavCommand::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.commands.ProtobufQuestNavCommand)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .questnav.protos.commands.QuestNavCommandType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // uint32 command_id = 2;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_command_id(), target);
  }

  // .questnav.protos.commands.ProtobufQuestNavPoseResetPayload pose_reset_payload = 10;
  if (_internal_has_pose_reset_payload()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::pose_reset_payload(this),
        _Internal::pose_reset_payload(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.commands.ProtobufQuestNavCommand)
  return target;
}

size_t ProtobufQuestNavCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:questnav.protos.commands.ProtobufQuestNavCommand)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .questnav.protos.commands.QuestNavCommandType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // uint32 command_id = 2;
  if (this->_internal_command_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_command_id());
  }

  switch (payload_case()) {
    // .questnav.protos.commands.ProtobufQuestNavPoseResetPayload pose_reset_payload = 10;
    case kPoseResetPayload: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.pose_reset_payload_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtobufQuestNavCommand::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProtobufQuestNavCommand::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtobufQuestNavCommand::GetClassData() const { return &_class_data_; }


void ProtobufQuestNavCommand::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavCommand*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavCommand&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.commands.ProtobufQuestNavCommand)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_command_id() != 0) {
    _this->_internal_set_command_id(from._internal_command_id());
  }
  switch (from.payload_case()) {
    case kPoseResetPayload: {
      _this->_internal_mutable_pose_reset_payload()->::questnav::protos::commands::ProtobufQuestNavPoseResetPayload::MergeFrom(
          from._internal_pose_reset_payload());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavCommand::CopyFrom(const ProtobufQuestNavCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.commands.ProtobufQuestNavCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufQuestNavCommand::IsInitialized() const {
  return true;
}

void ProtobufQuestNavCommand::InternalSwap(ProtobufQuestNavCommand* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_.command_id_)
      + sizeof(ProtobufQuestNavCommand::_impl_.command_id_)
      - PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommand, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtobufQuestNavCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_commands_2eproto_getter, &descriptor_table_commands_2eproto_once,
      file_level_metadata_commands_2eproto[1]);
}

// ===================================================================

class ProtobufQuestNavCommandResponse::_Internal {
 public:
};

ProtobufQuestNavCommandResponse::ProtobufQuestNavCommandResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.commands.ProtobufQuestNavCommandResponse)
}
ProtobufQuestNavCommandResponse::ProtobufQuestNavCommandResponse(const ProtobufQuestNavCommandResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProtobufQuestNavCommandResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.command_id_){}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.command_id_, &from._impl_.command_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.success_) -
    reinterpret_cast<char*>(&_impl_.command_id_)) + sizeof(_impl_.success_));
  // @@protoc_insertion_point(copy_constructor:questnav.protos.commands.ProtobufQuestNavCommandResponse)
}

inline void ProtobufQuestNavCommandResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.command_id_){0u}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ProtobufQuestNavCommandResponse::~ProtobufQuestNavCommandResponse() {
  // @@protoc_insertion_point(destructor:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtobufQuestNavCommandResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_message_.Destroy();
}

void ProtobufQuestNavCommandResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProtobufQuestNavCommandResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  ::memset(&_impl_.command_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.command_id_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtobufQuestNavCommandResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 command_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.command_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool success = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "questnav.protos.commands.ProtobufQuestNavCommandResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtobufQuestNavCommandResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 command_id = 1;
  if (this->_internal_command_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_command_id(), target);
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_success(), target);
  }

  // string error_message = 3;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "questnav.protos.commands.ProtobufQuestNavCommandResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  return target;
}

size_t ProtobufQuestNavCommandResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error_message = 3;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // uint32 command_id = 1;
  if (this->_internal_command_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_command_id());
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtobufQuestNavCommandResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProtobufQuestNavCommandResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtobufQuestNavCommandResponse::GetClassData() const { return &_class_data_; }


void ProtobufQuestNavCommandResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavCommandResponse*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavCommandResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_command_id() != 0) {
    _this->_internal_set_command_id(from._internal_command_id());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavCommandResponse::CopyFrom(const ProtobufQuestNavCommandResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.commands.ProtobufQuestNavCommandResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufQuestNavCommandResponse::IsInitialized() const {
  return true;
}

void ProtobufQuestNavCommandResponse::InternalSwap(ProtobufQuestNavCommandResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.success_)
      + sizeof(ProtobufQuestNavCommandResponse::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(ProtobufQuestNavCommandResponse, _impl_.command_id_)>(
          reinterpret_cast<char*>(&_impl_.command_id_),
          reinterpret_cast<char*>(&other->_impl_.command_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtobufQuestNavCommandResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_commands_2eproto_getter, &descriptor_table_commands_2eproto_once,
      file_level_metadata_commands_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace commands
}  // namespace protos
}  // namespace questnav
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload*
Arena::CreateMaybeMessage< ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload >(Arena* arena) {
  return Arena::CreateMessageInternal< ::questnav::protos::commands::ProtobufQuestNavPoseResetPayload >(arena);
}
template<> PROTOBUF_NOINLINE ::questnav::protos::commands::ProtobufQuestNavCommand*
Arena::CreateMaybeMessage< ::questnav::protos::commands::ProtobufQuestNavCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::questnav::protos::commands::ProtobufQuestNavCommand >(arena);
}
template<> PROTOBUF_NOINLINE ::questnav::protos::commands::ProtobufQuestNavCommandResponse*
Arena::CreateMaybeMessage< ::questnav::protos::commands::ProtobufQuestNavCommandResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::questnav::protos::commands::ProtobufQuestNavCommandResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
