// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

#include "protoh/data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace questnav {
namespace protos {
namespace data {
PROTOBUF_CONSTEXPR ProtobufQuestNavFrameData::ProtobufQuestNavFrameData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pose3d_)*/nullptr
  , /*decltype(_impl_.timestamp_)*/0
  , /*decltype(_impl_.frame_count_)*/0
  , /*decltype(_impl_.istracking_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProtobufQuestNavFrameDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavFrameDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavFrameDataDefaultTypeInternal() {}
  union {
    ProtobufQuestNavFrameData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavFrameDataDefaultTypeInternal _ProtobufQuestNavFrameData_default_instance_;
PROTOBUF_CONSTEXPR ProtobufQuestNavDeviceData::ProtobufQuestNavDeviceData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.tracking_lost_counter_)*/0
  , /*decltype(_impl_.battery_percent_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProtobufQuestNavDeviceDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtobufQuestNavDeviceDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtobufQuestNavDeviceDataDefaultTypeInternal() {}
  union {
    ProtobufQuestNavDeviceData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtobufQuestNavDeviceDataDefaultTypeInternal _ProtobufQuestNavDeviceData_default_instance_;
}  // namespace data
}  // namespace protos
}  // namespace questnav
static ::_pb::Metadata file_level_metadata_data_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_data_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_data_2eproto = nullptr;

const uint32_t TableStruct_data_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _impl_.frame_count_),
  PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _impl_.pose3d_),
  PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavFrameData, _impl_.istracking_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavDeviceData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavDeviceData, _impl_.tracking_lost_counter_),
  PROTOBUF_FIELD_OFFSET(::questnav::protos::data::ProtobufQuestNavDeviceData, _impl_.battery_percent_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::questnav::protos::data::ProtobufQuestNavFrameData)},
  { 10, -1, -1, sizeof(::questnav::protos::data::ProtobufQuestNavDeviceData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::questnav::protos::data::_ProtobufQuestNavFrameData_default_instance_._instance,
  &::questnav::protos::data::_ProtobufQuestNavDeviceData_default_instance_._instance,
};

const char descriptor_table_protodef_data_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\ndata.proto\022\024questnav.protos.data\032\020geom"
  "etry3d.proto\"\202\001\n\031ProtobufQuestNavFrameDa"
  "ta\022\023\n\013frame_count\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001"
  "(\001\022)\n\006pose3d\030\003 \001(\0132\031.wpi.proto.ProtobufP"
  "ose3d\022\022\n\nisTracking\030\004 \001(\010\"T\n\032ProtobufQue"
  "stNavDeviceData\022\035\n\025tracking_lost_counter"
  "\030\001 \001(\005\022\027\n\017battery_percent\030\003 \001(\005BC\n%gg.qu"
  "estnav.questnav.protos.generated\252\002\031Quest"
  "Nav.Protos.Generatedb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_data_2eproto_deps[1] = {
  &::descriptor_table_geometry3d_2eproto,
};
static ::_pbi::once_flag descriptor_table_data_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_data_2eproto = {
    false, false, 348, descriptor_table_protodef_data_2eproto,
    "data.proto",
    &descriptor_table_data_2eproto_once, descriptor_table_data_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_data_2eproto::offsets,
    file_level_metadata_data_2eproto, file_level_enum_descriptors_data_2eproto,
    file_level_service_descriptors_data_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_data_2eproto_getter() {
  return &descriptor_table_data_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_data_2eproto(&descriptor_table_data_2eproto);
namespace questnav {
namespace protos {
namespace data {

// ===================================================================

class ProtobufQuestNavFrameData::_Internal {
 public:
  static const ::wpi::proto::ProtobufPose3d& pose3d(const ProtobufQuestNavFrameData* msg);
};

const ::wpi::proto::ProtobufPose3d&
ProtobufQuestNavFrameData::_Internal::pose3d(const ProtobufQuestNavFrameData* msg) {
  return *msg->_impl_.pose3d_;
}
void ProtobufQuestNavFrameData::clear_pose3d() {
  if (GetArenaForAllocation() == nullptr && _impl_.pose3d_ != nullptr) {
    delete _impl_.pose3d_;
  }
  _impl_.pose3d_ = nullptr;
}
ProtobufQuestNavFrameData::ProtobufQuestNavFrameData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.data.ProtobufQuestNavFrameData)
}
ProtobufQuestNavFrameData::ProtobufQuestNavFrameData(const ProtobufQuestNavFrameData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProtobufQuestNavFrameData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pose3d_){nullptr}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.frame_count_){}
    , decltype(_impl_.istracking_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_pose3d()) {
    _this->_impl_.pose3d_ = new ::wpi::proto::ProtobufPose3d(*from._impl_.pose3d_);
  }
  ::memcpy(&_impl_.timestamp_, &from._impl_.timestamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.istracking_) -
    reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.istracking_));
  // @@protoc_insertion_point(copy_constructor:questnav.protos.data.ProtobufQuestNavFrameData)
}

inline void ProtobufQuestNavFrameData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pose3d_){nullptr}
    , decltype(_impl_.timestamp_){0}
    , decltype(_impl_.frame_count_){0}
    , decltype(_impl_.istracking_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProtobufQuestNavFrameData::~ProtobufQuestNavFrameData() {
  // @@protoc_insertion_point(destructor:questnav.protos.data.ProtobufQuestNavFrameData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtobufQuestNavFrameData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.pose3d_;
}

void ProtobufQuestNavFrameData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProtobufQuestNavFrameData::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.data.ProtobufQuestNavFrameData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.pose3d_ != nullptr) {
    delete _impl_.pose3d_;
  }
  _impl_.pose3d_ = nullptr;
  ::memset(&_impl_.timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.istracking_) -
      reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.istracking_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtobufQuestNavFrameData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 frame_count = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.frame_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double timestamp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // .wpi.proto.ProtobufPose3d pose3d = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_pose3d(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool isTracking = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.istracking_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtobufQuestNavFrameData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.data.ProtobufQuestNavFrameData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 frame_count = 1;
  if (this->_internal_frame_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_frame_count(), target);
  }

  // double timestamp = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_timestamp = this->_internal_timestamp();
  uint64_t raw_timestamp;
  memcpy(&raw_timestamp, &tmp_timestamp, sizeof(tmp_timestamp));
  if (raw_timestamp != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_timestamp(), target);
  }

  // .wpi.proto.ProtobufPose3d pose3d = 3;
  if (this->_internal_has_pose3d()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::pose3d(this),
        _Internal::pose3d(this).GetCachedSize(), target, stream);
  }

  // bool isTracking = 4;
  if (this->_internal_istracking() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_istracking(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.data.ProtobufQuestNavFrameData)
  return target;
}

size_t ProtobufQuestNavFrameData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:questnav.protos.data.ProtobufQuestNavFrameData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .wpi.proto.ProtobufPose3d pose3d = 3;
  if (this->_internal_has_pose3d()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.pose3d_);
  }

  // double timestamp = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_timestamp = this->_internal_timestamp();
  uint64_t raw_timestamp;
  memcpy(&raw_timestamp, &tmp_timestamp, sizeof(tmp_timestamp));
  if (raw_timestamp != 0) {
    total_size += 1 + 8;
  }

  // int32 frame_count = 1;
  if (this->_internal_frame_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_frame_count());
  }

  // bool isTracking = 4;
  if (this->_internal_istracking() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtobufQuestNavFrameData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProtobufQuestNavFrameData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtobufQuestNavFrameData::GetClassData() const { return &_class_data_; }


void ProtobufQuestNavFrameData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavFrameData*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavFrameData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.data.ProtobufQuestNavFrameData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_pose3d()) {
    _this->_internal_mutable_pose3d()->::wpi::proto::ProtobufPose3d::MergeFrom(
        from._internal_pose3d());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_timestamp = from._internal_timestamp();
  uint64_t raw_timestamp;
  memcpy(&raw_timestamp, &tmp_timestamp, sizeof(tmp_timestamp));
  if (raw_timestamp != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (from._internal_frame_count() != 0) {
    _this->_internal_set_frame_count(from._internal_frame_count());
  }
  if (from._internal_istracking() != 0) {
    _this->_internal_set_istracking(from._internal_istracking());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavFrameData::CopyFrom(const ProtobufQuestNavFrameData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.data.ProtobufQuestNavFrameData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufQuestNavFrameData::IsInitialized() const {
  return true;
}

void ProtobufQuestNavFrameData::InternalSwap(ProtobufQuestNavFrameData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.istracking_)
      + sizeof(ProtobufQuestNavFrameData::_impl_.istracking_)
      - PROTOBUF_FIELD_OFFSET(ProtobufQuestNavFrameData, _impl_.pose3d_)>(
          reinterpret_cast<char*>(&_impl_.pose3d_),
          reinterpret_cast<char*>(&other->_impl_.pose3d_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtobufQuestNavFrameData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_data_2eproto_getter, &descriptor_table_data_2eproto_once,
      file_level_metadata_data_2eproto[0]);
}

// ===================================================================

class ProtobufQuestNavDeviceData::_Internal {
 public:
};

ProtobufQuestNavDeviceData::ProtobufQuestNavDeviceData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:questnav.protos.data.ProtobufQuestNavDeviceData)
}
ProtobufQuestNavDeviceData::ProtobufQuestNavDeviceData(const ProtobufQuestNavDeviceData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProtobufQuestNavDeviceData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.tracking_lost_counter_){}
    , decltype(_impl_.battery_percent_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.tracking_lost_counter_, &from._impl_.tracking_lost_counter_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.battery_percent_) -
    reinterpret_cast<char*>(&_impl_.tracking_lost_counter_)) + sizeof(_impl_.battery_percent_));
  // @@protoc_insertion_point(copy_constructor:questnav.protos.data.ProtobufQuestNavDeviceData)
}

inline void ProtobufQuestNavDeviceData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.tracking_lost_counter_){0}
    , decltype(_impl_.battery_percent_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProtobufQuestNavDeviceData::~ProtobufQuestNavDeviceData() {
  // @@protoc_insertion_point(destructor:questnav.protos.data.ProtobufQuestNavDeviceData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProtobufQuestNavDeviceData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ProtobufQuestNavDeviceData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProtobufQuestNavDeviceData::Clear() {
// @@protoc_insertion_point(message_clear_start:questnav.protos.data.ProtobufQuestNavDeviceData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.tracking_lost_counter_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.battery_percent_) -
      reinterpret_cast<char*>(&_impl_.tracking_lost_counter_)) + sizeof(_impl_.battery_percent_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProtobufQuestNavDeviceData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 tracking_lost_counter = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.tracking_lost_counter_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 battery_percent = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.battery_percent_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProtobufQuestNavDeviceData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:questnav.protos.data.ProtobufQuestNavDeviceData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 tracking_lost_counter = 1;
  if (this->_internal_tracking_lost_counter() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_tracking_lost_counter(), target);
  }

  // int32 battery_percent = 3;
  if (this->_internal_battery_percent() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_battery_percent(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:questnav.protos.data.ProtobufQuestNavDeviceData)
  return target;
}

size_t ProtobufQuestNavDeviceData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:questnav.protos.data.ProtobufQuestNavDeviceData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 tracking_lost_counter = 1;
  if (this->_internal_tracking_lost_counter() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tracking_lost_counter());
  }

  // int32 battery_percent = 3;
  if (this->_internal_battery_percent() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_battery_percent());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProtobufQuestNavDeviceData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProtobufQuestNavDeviceData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProtobufQuestNavDeviceData::GetClassData() const { return &_class_data_; }


void ProtobufQuestNavDeviceData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProtobufQuestNavDeviceData*>(&to_msg);
  auto& from = static_cast<const ProtobufQuestNavDeviceData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:questnav.protos.data.ProtobufQuestNavDeviceData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_tracking_lost_counter() != 0) {
    _this->_internal_set_tracking_lost_counter(from._internal_tracking_lost_counter());
  }
  if (from._internal_battery_percent() != 0) {
    _this->_internal_set_battery_percent(from._internal_battery_percent());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProtobufQuestNavDeviceData::CopyFrom(const ProtobufQuestNavDeviceData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:questnav.protos.data.ProtobufQuestNavDeviceData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufQuestNavDeviceData::IsInitialized() const {
  return true;
}

void ProtobufQuestNavDeviceData::InternalSwap(ProtobufQuestNavDeviceData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProtobufQuestNavDeviceData, _impl_.battery_percent_)
      + sizeof(ProtobufQuestNavDeviceData::_impl_.battery_percent_)
      - PROTOBUF_FIELD_OFFSET(ProtobufQuestNavDeviceData, _impl_.tracking_lost_counter_)>(
          reinterpret_cast<char*>(&_impl_.tracking_lost_counter_),
          reinterpret_cast<char*>(&other->_impl_.tracking_lost_counter_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProtobufQuestNavDeviceData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_data_2eproto_getter, &descriptor_table_data_2eproto_once,
      file_level_metadata_data_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace protos
}  // namespace questnav
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::questnav::protos::data::ProtobufQuestNavFrameData*
Arena::CreateMaybeMessage< ::questnav::protos::data::ProtobufQuestNavFrameData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::questnav::protos::data::ProtobufQuestNavFrameData >(arena);
}
template<> PROTOBUF_NOINLINE ::questnav::protos::data::ProtobufQuestNavDeviceData*
Arena::CreateMaybeMessage< ::questnav::protos::data::ProtobufQuestNavDeviceData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::questnav::protos::data::ProtobufQuestNavDeviceData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
