// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_data_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_data_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "geometry3d.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_data_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_data_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_data_2eproto;
namespace questnav {
namespace protos {
namespace data {
class ProtobufQuestNavDeviceData;
struct ProtobufQuestNavDeviceDataDefaultTypeInternal;
extern ProtobufQuestNavDeviceDataDefaultTypeInternal _ProtobufQuestNavDeviceData_default_instance_;
class ProtobufQuestNavFrameData;
struct ProtobufQuestNavFrameDataDefaultTypeInternal;
extern ProtobufQuestNavFrameDataDefaultTypeInternal _ProtobufQuestNavFrameData_default_instance_;
}  // namespace data
}  // namespace protos
}  // namespace questnav
PROTOBUF_NAMESPACE_OPEN
template<> ::questnav::protos::data::ProtobufQuestNavDeviceData* Arena::CreateMaybeMessage<::questnav::protos::data::ProtobufQuestNavDeviceData>(Arena*);
template<> ::questnav::protos::data::ProtobufQuestNavFrameData* Arena::CreateMaybeMessage<::questnav::protos::data::ProtobufQuestNavFrameData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace questnav {
namespace protos {
namespace data {

// ===================================================================

class ProtobufQuestNavFrameData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:questnav.protos.data.ProtobufQuestNavFrameData) */ {
 public:
  inline ProtobufQuestNavFrameData() : ProtobufQuestNavFrameData(nullptr) {}
  ~ProtobufQuestNavFrameData() override;
  explicit PROTOBUF_CONSTEXPR ProtobufQuestNavFrameData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProtobufQuestNavFrameData(const ProtobufQuestNavFrameData& from);
  ProtobufQuestNavFrameData(ProtobufQuestNavFrameData&& from) noexcept
    : ProtobufQuestNavFrameData() {
    *this = ::std::move(from);
  }

  inline ProtobufQuestNavFrameData& operator=(const ProtobufQuestNavFrameData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufQuestNavFrameData& operator=(ProtobufQuestNavFrameData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufQuestNavFrameData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufQuestNavFrameData* internal_default_instance() {
    return reinterpret_cast<const ProtobufQuestNavFrameData*>(
               &_ProtobufQuestNavFrameData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ProtobufQuestNavFrameData& a, ProtobufQuestNavFrameData& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtobufQuestNavFrameData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufQuestNavFrameData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufQuestNavFrameData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProtobufQuestNavFrameData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProtobufQuestNavFrameData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProtobufQuestNavFrameData& from) {
    ProtobufQuestNavFrameData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufQuestNavFrameData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "questnav.protos.data.ProtobufQuestNavFrameData";
  }
  protected:
  explicit ProtobufQuestNavFrameData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPose3DFieldNumber = 3,
    kTimestampFieldNumber = 2,
    kFrameCountFieldNumber = 1,
    kIsTrackingFieldNumber = 4,
  };
  // .wpi.proto.ProtobufPose3d pose3d = 3;
  bool has_pose3d() const;
  private:
  bool _internal_has_pose3d() const;
  public:
  void clear_pose3d();
  const ::wpi::proto::ProtobufPose3d& pose3d() const;
  PROTOBUF_NODISCARD ::wpi::proto::ProtobufPose3d* release_pose3d();
  ::wpi::proto::ProtobufPose3d* mutable_pose3d();
  void set_allocated_pose3d(::wpi::proto::ProtobufPose3d* pose3d);
  private:
  const ::wpi::proto::ProtobufPose3d& _internal_pose3d() const;
  ::wpi::proto::ProtobufPose3d* _internal_mutable_pose3d();
  public:
  void unsafe_arena_set_allocated_pose3d(
      ::wpi::proto::ProtobufPose3d* pose3d);
  ::wpi::proto::ProtobufPose3d* unsafe_arena_release_pose3d();

  // double timestamp = 2;
  void clear_timestamp();
  double timestamp() const;
  void set_timestamp(double value);
  private:
  double _internal_timestamp() const;
  void _internal_set_timestamp(double value);
  public:

  // int32 frame_count = 1;
  void clear_frame_count();
  int32_t frame_count() const;
  void set_frame_count(int32_t value);
  private:
  int32_t _internal_frame_count() const;
  void _internal_set_frame_count(int32_t value);
  public:

  // bool isTracking = 4;
  void clear_istracking();
  bool istracking() const;
  void set_istracking(bool value);
  private:
  bool _internal_istracking() const;
  void _internal_set_istracking(bool value);
  public:

  // @@protoc_insertion_point(class_scope:questnav.protos.data.ProtobufQuestNavFrameData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::wpi::proto::ProtobufPose3d* pose3d_;
    double timestamp_;
    int32_t frame_count_;
    bool istracking_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_data_2eproto;
};
// -------------------------------------------------------------------

class ProtobufQuestNavDeviceData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:questnav.protos.data.ProtobufQuestNavDeviceData) */ {
 public:
  inline ProtobufQuestNavDeviceData() : ProtobufQuestNavDeviceData(nullptr) {}
  ~ProtobufQuestNavDeviceData() override;
  explicit PROTOBUF_CONSTEXPR ProtobufQuestNavDeviceData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProtobufQuestNavDeviceData(const ProtobufQuestNavDeviceData& from);
  ProtobufQuestNavDeviceData(ProtobufQuestNavDeviceData&& from) noexcept
    : ProtobufQuestNavDeviceData() {
    *this = ::std::move(from);
  }

  inline ProtobufQuestNavDeviceData& operator=(const ProtobufQuestNavDeviceData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufQuestNavDeviceData& operator=(ProtobufQuestNavDeviceData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufQuestNavDeviceData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtobufQuestNavDeviceData* internal_default_instance() {
    return reinterpret_cast<const ProtobufQuestNavDeviceData*>(
               &_ProtobufQuestNavDeviceData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ProtobufQuestNavDeviceData& a, ProtobufQuestNavDeviceData& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtobufQuestNavDeviceData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufQuestNavDeviceData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufQuestNavDeviceData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProtobufQuestNavDeviceData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProtobufQuestNavDeviceData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProtobufQuestNavDeviceData& from) {
    ProtobufQuestNavDeviceData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufQuestNavDeviceData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "questnav.protos.data.ProtobufQuestNavDeviceData";
  }
  protected:
  explicit ProtobufQuestNavDeviceData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTrackingLostCounterFieldNumber = 1,
    kBatteryPercentFieldNumber = 3,
  };
  // int32 tracking_lost_counter = 1;
  void clear_tracking_lost_counter();
  int32_t tracking_lost_counter() const;
  void set_tracking_lost_counter(int32_t value);
  private:
  int32_t _internal_tracking_lost_counter() const;
  void _internal_set_tracking_lost_counter(int32_t value);
  public:

  // int32 battery_percent = 3;
  void clear_battery_percent();
  int32_t battery_percent() const;
  void set_battery_percent(int32_t value);
  private:
  int32_t _internal_battery_percent() const;
  void _internal_set_battery_percent(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:questnav.protos.data.ProtobufQuestNavDeviceData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t tracking_lost_counter_;
    int32_t battery_percent_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_data_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtobufQuestNavFrameData

// int32 frame_count = 1;
inline void ProtobufQuestNavFrameData::clear_frame_count() {
  _impl_.frame_count_ = 0;
}
inline int32_t ProtobufQuestNavFrameData::_internal_frame_count() const {
  return _impl_.frame_count_;
}
inline int32_t ProtobufQuestNavFrameData::frame_count() const {
  // @@protoc_insertion_point(field_get:questnav.protos.data.ProtobufQuestNavFrameData.frame_count)
  return _internal_frame_count();
}
inline void ProtobufQuestNavFrameData::_internal_set_frame_count(int32_t value) {
  
  _impl_.frame_count_ = value;
}
inline void ProtobufQuestNavFrameData::set_frame_count(int32_t value) {
  _internal_set_frame_count(value);
  // @@protoc_insertion_point(field_set:questnav.protos.data.ProtobufQuestNavFrameData.frame_count)
}

// double timestamp = 2;
inline void ProtobufQuestNavFrameData::clear_timestamp() {
  _impl_.timestamp_ = 0;
}
inline double ProtobufQuestNavFrameData::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline double ProtobufQuestNavFrameData::timestamp() const {
  // @@protoc_insertion_point(field_get:questnav.protos.data.ProtobufQuestNavFrameData.timestamp)
  return _internal_timestamp();
}
inline void ProtobufQuestNavFrameData::_internal_set_timestamp(double value) {
  
  _impl_.timestamp_ = value;
}
inline void ProtobufQuestNavFrameData::set_timestamp(double value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:questnav.protos.data.ProtobufQuestNavFrameData.timestamp)
}

// .wpi.proto.ProtobufPose3d pose3d = 3;
inline bool ProtobufQuestNavFrameData::_internal_has_pose3d() const {
  return this != internal_default_instance() && _impl_.pose3d_ != nullptr;
}
inline bool ProtobufQuestNavFrameData::has_pose3d() const {
  return _internal_has_pose3d();
}
inline const ::wpi::proto::ProtobufPose3d& ProtobufQuestNavFrameData::_internal_pose3d() const {
  const ::wpi::proto::ProtobufPose3d* p = _impl_.pose3d_;
  return p != nullptr ? *p : reinterpret_cast<const ::wpi::proto::ProtobufPose3d&>(
      ::wpi::proto::_ProtobufPose3d_default_instance_);
}
inline const ::wpi::proto::ProtobufPose3d& ProtobufQuestNavFrameData::pose3d() const {
  // @@protoc_insertion_point(field_get:questnav.protos.data.ProtobufQuestNavFrameData.pose3d)
  return _internal_pose3d();
}
inline void ProtobufQuestNavFrameData::unsafe_arena_set_allocated_pose3d(
    ::wpi::proto::ProtobufPose3d* pose3d) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pose3d_);
  }
  _impl_.pose3d_ = pose3d;
  if (pose3d) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:questnav.protos.data.ProtobufQuestNavFrameData.pose3d)
}
inline ::wpi::proto::ProtobufPose3d* ProtobufQuestNavFrameData::release_pose3d() {
  
  ::wpi::proto::ProtobufPose3d* temp = _impl_.pose3d_;
  _impl_.pose3d_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::wpi::proto::ProtobufPose3d* ProtobufQuestNavFrameData::unsafe_arena_release_pose3d() {
  // @@protoc_insertion_point(field_release:questnav.protos.data.ProtobufQuestNavFrameData.pose3d)
  
  ::wpi::proto::ProtobufPose3d* temp = _impl_.pose3d_;
  _impl_.pose3d_ = nullptr;
  return temp;
}
inline ::wpi::proto::ProtobufPose3d* ProtobufQuestNavFrameData::_internal_mutable_pose3d() {
  
  if (_impl_.pose3d_ == nullptr) {
    auto* p = CreateMaybeMessage<::wpi::proto::ProtobufPose3d>(GetArenaForAllocation());
    _impl_.pose3d_ = p;
  }
  return _impl_.pose3d_;
}
inline ::wpi::proto::ProtobufPose3d* ProtobufQuestNavFrameData::mutable_pose3d() {
  ::wpi::proto::ProtobufPose3d* _msg = _internal_mutable_pose3d();
  // @@protoc_insertion_point(field_mutable:questnav.protos.data.ProtobufQuestNavFrameData.pose3d)
  return _msg;
}
inline void ProtobufQuestNavFrameData::set_allocated_pose3d(::wpi::proto::ProtobufPose3d* pose3d) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pose3d_);
  }
  if (pose3d) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose3d));
    if (message_arena != submessage_arena) {
      pose3d = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pose3d, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pose3d_ = pose3d;
  // @@protoc_insertion_point(field_set_allocated:questnav.protos.data.ProtobufQuestNavFrameData.pose3d)
}

// bool isTracking = 4;
inline void ProtobufQuestNavFrameData::clear_istracking() {
  _impl_.istracking_ = false;
}
inline bool ProtobufQuestNavFrameData::_internal_istracking() const {
  return _impl_.istracking_;
}
inline bool ProtobufQuestNavFrameData::istracking() const {
  // @@protoc_insertion_point(field_get:questnav.protos.data.ProtobufQuestNavFrameData.isTracking)
  return _internal_istracking();
}
inline void ProtobufQuestNavFrameData::_internal_set_istracking(bool value) {
  
  _impl_.istracking_ = value;
}
inline void ProtobufQuestNavFrameData::set_istracking(bool value) {
  _internal_set_istracking(value);
  // @@protoc_insertion_point(field_set:questnav.protos.data.ProtobufQuestNavFrameData.isTracking)
}

// -------------------------------------------------------------------

// ProtobufQuestNavDeviceData

// int32 tracking_lost_counter = 1;
inline void ProtobufQuestNavDeviceData::clear_tracking_lost_counter() {
  _impl_.tracking_lost_counter_ = 0;
}
inline int32_t ProtobufQuestNavDeviceData::_internal_tracking_lost_counter() const {
  return _impl_.tracking_lost_counter_;
}
inline int32_t ProtobufQuestNavDeviceData::tracking_lost_counter() const {
  // @@protoc_insertion_point(field_get:questnav.protos.data.ProtobufQuestNavDeviceData.tracking_lost_counter)
  return _internal_tracking_lost_counter();
}
inline void ProtobufQuestNavDeviceData::_internal_set_tracking_lost_counter(int32_t value) {
  
  _impl_.tracking_lost_counter_ = value;
}
inline void ProtobufQuestNavDeviceData::set_tracking_lost_counter(int32_t value) {
  _internal_set_tracking_lost_counter(value);
  // @@protoc_insertion_point(field_set:questnav.protos.data.ProtobufQuestNavDeviceData.tracking_lost_counter)
}

// int32 battery_percent = 3;
inline void ProtobufQuestNavDeviceData::clear_battery_percent() {
  _impl_.battery_percent_ = 0;
}
inline int32_t ProtobufQuestNavDeviceData::_internal_battery_percent() const {
  return _impl_.battery_percent_;
}
inline int32_t ProtobufQuestNavDeviceData::battery_percent() const {
  // @@protoc_insertion_point(field_get:questnav.protos.data.ProtobufQuestNavDeviceData.battery_percent)
  return _internal_battery_percent();
}
inline void ProtobufQuestNavDeviceData::_internal_set_battery_percent(int32_t value) {
  
  _impl_.battery_percent_ = value;
}
inline void ProtobufQuestNavDeviceData::set_battery_percent(int32_t value) {
  _internal_set_battery_percent(value);
  // @@protoc_insertion_point(field_set:questnav.protos.data.ProtobufQuestNavDeviceData.battery_percent)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace protos
}  // namespace questnav

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_data_2eproto
